name: Build Phantom.kext

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # Sử dụng runner có sẵn Xcode 15.2
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          git submodule update --init --recursive

      - name: Build .kext
        run: |
          xcodebuild -project Phantom.xcodeproj -scheme Phantom -configuration Release build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Phantom.kext
          path: build/Release/Phantom.kext
